"""Tests for migrate_legacy_store.py — the one-shot, explicit legacy-store
migration (REQ-18, REQ-23, REQ-26).

The Git-based proof (`test_lesson_bodies_and_descriptions_survive_migration_
byte_for_byte`, `test_guide_concept_metadata_and_charter_prose`,
`test_lesson_and_guide_concept_counts_are_293_and_1`) recomputes its baseline
from Git at the pinned pre-migration commit — never from a committed
snapshot file generated by this same session — so a green post-migration
validator cannot conceal lost text (plan.md Risk 1). These three tests only
pass once the real repository store at `docs/loom/memory/` has actually been
migrated; they are the acceptance evidence for that real migration, not a
synthetic-fixture test.

The remaining tests exercise `migrate()`/`is_legacy_store()`/
`introducing_commit()` against synthetic stores built under `tmp_path`, and
the negative `no-implicit-migration-and-no-legacy-writer` assertions.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPTS_DIR.parent.parent
STORE = REPO_ROOT / "docs" / "loom" / "memory"
PRE_MIGRATION_SHA = "bd7c080a0eea2517436fbd1c9ad8d19224528245"
sys.path.insert(0, str(SCRIPTS_DIR))

import loom_memory as lm  # noqa: E402
import migrate_legacy_store as mls  # noqa: E402


# ---------------------------------------------------------------------------
# Fixture helpers (synthetic stores)
# ---------------------------------------------------------------------------


def _write(store: Path, rel: str, text: str) -> None:
    path = store / rel
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _legacy_concept(name: str, description: str, *, type_: str | None = "practice", origin: str | None = "a fixture origin") -> str:
    lines = ["---", f"name: {name}", f"description: {description}"]
    if type_ is not None:
        lines.append(f"type: {type_}")
    if origin is not None:
        lines.append(f"origin: {origin}")
    lines.append("---")
    lines.append("")
    lines.append("The fact body.")
    lines.append("")
    return "\n".join(lines)


def _legacy_readme(index_lines: list[str], *, charter: str = "# Charter\n\nSome prose.\n") -> str:
    body = charter.rstrip("\n") + "\n\n## Index\n\n" + "\n".join(index_lines) + "\n"
    return body


def _make_legacy_store(store: Path) -> None:
    store.mkdir(parents=True)
    _write(store, "README.md", _legacy_readme(["[a-fact](a-fact.md) — A description."]))
    _write(store, "a-fact.md", _legacy_concept("a-fact", "A description."))


def _init_git_repo(root: Path) -> None:
    for cmd in (
        ["git", "init", "-q"],
        ["git", "config", "user.email", "test@example.com"],
        ["git", "config", "user.name", "Test"],
    ):
        subprocess.run(cmd, cwd=root, check=True, capture_output=True)


def _commit_all(root: Path, message: str) -> None:
    subprocess.run(["git", "add", "-A"], cwd=root, check=True, capture_output=True)
    subprocess.run(["git", "commit", "-q", "-m", message], cwd=root, check=True, capture_output=True)


# ---------------------------------------------------------------------------
# Acceptance A5 positive: lesson-count-body-description-origin-fingerprints
# (Git-based proof, against the REAL repository store)
# ---------------------------------------------------------------------------


def _git_show(rel_path: str) -> str:
    result = subprocess.run(
        ["git", "show", f"{PRE_MIGRATION_SHA}:{rel_path}"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    return result.stdout


def _pre_migration_lesson_paths() -> list[str]:
    result = subprocess.run(
        ["git", "ls-tree", "-r", "--name-only", PRE_MIGRATION_SHA, "--", "docs/loom/memory"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    paths = [line for line in result.stdout.splitlines() if line.strip()]
    return sorted(p for p in paths if not p.endswith("/README.md") and not p.endswith("/index.md"))


def test_lesson_and_guide_concept_counts_are_293_and_1():
    """A5 positive — counted separately, per REQ-18."""
    lesson_paths = _pre_migration_lesson_paths()
    assert len(lesson_paths) == 293

    post_lesson_files = sorted(p for p in STORE.glob("*.md") if p.name not in ("README.md", "index.md"))
    assert len(post_lesson_files) == 293

    guide_files = [
        p
        for p in STORE.glob("*.md")
        if p.name != "index.md" and lm.parse_frontmatter(p.read_text(encoding="utf-8")).get("type") == lm.GUIDE_TYPE
    ]
    assert len(guide_files) == 1
    assert guide_files[0].name == "README.md"


def test_lesson_bodies_and_descriptions_survive_migration_byte_for_byte():
    """A5 positive — recomputed from Git at PRE_MIGRATION_SHA, never from a
    committed snapshot file (plan.md Risk 1)."""
    lesson_paths = _pre_migration_lesson_paths()
    assert lesson_paths, "baseline must be non-empty or this proof is vacuous"

    checked = 0
    origin_less_count = 0
    for rel in lesson_paths:
        pre_text = _git_show(rel)
        pre_fm_lines, pre_body = mls.split_legacy(pre_text)
        pre_fm = mls.parse_legacy_frontmatter(pre_fm_lines)

        post_path = REPO_ROOT / rel
        assert post_path.is_file(), f"{rel} missing from the migrated working tree"
        post_text = post_path.read_text(encoding="utf-8")
        post_fm_lines, post_body = mls.split_legacy(post_text)
        post_fm = lm.parse_frontmatter(post_text)

        assert post_body == pre_body, f"{rel}: body drifted"
        assert post_fm["description"] == pre_fm["description"], f"{rel}: description drifted"

        sources = post_fm["sources"]
        assert isinstance(sources, list) and sources, f"{rel}: sources missing post-migration"
        resource = sources[0]["resource"]
        if "origin" in pre_fm:
            assert resource == pre_fm["origin"], f"{rel}: origin fingerprint drifted"
        else:
            origin_less_count += 1
            assert resource.startswith("introducing commit "), (
                f"{rel}: origin-less lesson must derive its resource from the introducing "
                f"commit, got {resource!r}"
            )
        checked += 1

    assert checked == 293
    assert origin_less_count == 1


def test_guide_concept_metadata_and_charter_prose():
    """A5 positive — the guide concept, compared separately from lessons.

    Narrowed 2026-09-10 (W3-01b, see decisions.md): the original assertion
    here was a full-body byte-match against the PRE-MIGRATION charter, which
    also blocks any later deliberate correction to the README's prose (the
    OKF-migration W3-01 task left `## Format — one fact per file` describing
    a legacy `type: practice | gotcha | process` / `origin:` shape and a
    deleted `scripts/check_loom_memory_integrity.py` command — a charter that
    teaches a deleted command is a defect, and REQ-5/REQ-17/REQ-26 do not
    freeze the README's prose, only the migration's fidelity).
    Splitting the comparison at the `## Format` heading keeps the strong
    byte-for-byte proof over everything migration must not have touched
    (title, blockquote, the jurisdiction table, "When to record") — a
    wholesale rewrite anywhere in that region still fails this test — while
    permitting the Format section's own documented, separately-committed
    fix. Within the Format section, the specific load-bearing clauses that
    fix did NOT touch (the filename-slug rule, the description-vs-body
    test, the recorded-instance case study, the forward-only binding
    clause) are still pinned verbatim against the pre-migration text, so an
    accidental loss of THOSE clauses during a future Format-section edit
    still fails here too.
    """
    pre_text = _git_show("docs/loom/memory/README.md")
    charter_before = mls._extract_charter(pre_text)

    post_text = (STORE / "README.md").read_text(encoding="utf-8")
    post_fm = lm.parse_frontmatter(post_text)
    assert post_fm is not None
    assert post_fm["type"] == lm.GUIDE_TYPE
    assert post_fm["name"] == "README"
    assert isinstance(post_fm["description"], str) and post_fm["description"].strip()
    sources = post_fm["sources"]
    assert isinstance(sources, list) and len(sources) == 1
    resource = sources[0]["resource"]
    expected_sha = mls.introducing_commit(REPO_ROOT, "docs/loom/memory/README.md")
    assert expected_sha in resource
    assert len(expected_sha) == 40

    post_fm_lines, post_body = mls.split_legacy(post_text)
    # `migrate()` inserts exactly one blank line between the frontmatter's
    # closing `---` and the charter body (the same spacing convention every
    # lesson concept already uses) — strip that one separator, not part of
    # the charter prose itself, before comparing.
    charter_before = charter_before.lstrip("\n")
    post_body = post_body.lstrip("\n").rstrip("\n") + "\n"
    assert "[a-backticked-token-with-a-slash" not in post_body  # first index entry line, gone

    FORMAT_HEADING = "## Format — one fact per file"
    before_preamble, _, before_format = charter_before.partition(FORMAT_HEADING)
    post_preamble, _, post_format = post_body.partition(FORMAT_HEADING)
    assert before_format and post_format, "both texts must still carry the Format heading"
    # Everything migration must not have touched — title, blockquote, the
    # jurisdiction table, "When to record" — byte-for-byte, unnarrowed.
    assert post_preamble == before_preamble

    # Load-bearing clauses inside the Format section that this task's README
    # fix did not touch, pinned verbatim against the pre-migration text so a
    # future edit cannot silently drop them while narrowing this test.
    load_bearing_clauses = [
        "The file is named `<name>.md` — the frontmatter `name` slug IS the\n"
        "filename, so index links never diverge from filenames.\n",
        "**The `description` states the durable rule; it never states which tools\n"
        "currently exist.**",
        "**The test** — one question, applied clause by clause: *would this clause\n"
        "become false if someone shipped, removed, or reconfigured a tool?* If yes,\n"
        "it is body content. If no, it may stay.\n"
        "\n"
        "- Fails the test, so belongs in the body: \"X is not yet mechanised\",\n"
        "  \"no script covers Z\", \"the check runs in CI but not in pytest\",\n"
        "  \"mechanized in `<some-tool>`\".\n"
        "- Passes, so may stay: a permanent property of the method itself — \"a\n"
        "  proposition restated in synonyms is invisible to any string search\" is\n"
        "  true of string search, not of any particular script.\n",
        "Recorded instance: an entry whose description presented a hard-wrap leak\n"
        "as open while its own body stated the leak was mechanised — the store's\n"
        "integrity checker exited 0 throughout, because byte-identity to the index\n"
        "is the invariant it enforces, and truth against the body is not checkable\n"
        "(`docs/loom/audits/2026-08-04-docs-review-convergence-experiment.md`).\n"
        "`docs/loom/memory/measure-a-checks-fire-rate-before-building-it.md`\n"
        "records why this is a format rule and not a detector.\n",
        "**Binding: forward-only, and the store does not yet conform.** The rule\n"
        "governs an entry when it is written and when its description is next\n"
        "edited; it does not oblige a retrofit sweep. Fix a non-conforming\n"
        "description on its next touch.\n",
    ]
    for clause in load_bearing_clauses:
        assert clause in before_format, f"pre-migration Format section lost an anchor clause:\n{clause}"
        assert clause in post_format, f"current Format section dropped a load-bearing clause:\n{clause}"


def test_migrated_store_validates_clean_and_regenerates_idempotently():
    assert lm.validate_bundle(STORE) == []
    first = (STORE / "index.md").read_text(encoding="utf-8")
    lm.regenerate_index(STORE)
    second = (STORE / "index.md").read_text(encoding="utf-8")
    assert first == second


# ---------------------------------------------------------------------------
# Synthetic-store unit tests for migrate()/is_legacy_store()
# ---------------------------------------------------------------------------


def test_migrate_transforms_a_legacy_store_into_a_valid_okf_profile(tmp_path):
    repo_root = tmp_path / "repo"
    store = repo_root / "docs" / "loom" / "memory"
    _make_legacy_store(store)
    _init_git_repo(repo_root)
    _commit_all(repo_root, "initial")

    assert mls.is_legacy_store(store) is True
    result = mls.migrate(store, repo_root)

    assert result.lessons == 1
    assert result.guide == 1
    assert lm.validate_bundle(store) == []

    fact_fm = lm.parse_frontmatter((store / "a-fact.md").read_text(encoding="utf-8"))
    assert fact_fm["type"] == "practice"
    assert fact_fm["sources"][0]["resource"] == "a fixture origin"

    readme_fm = lm.parse_frontmatter((store / "README.md").read_text(encoding="utf-8"))
    assert readme_fm["type"] == lm.GUIDE_TYPE
    assert readme_fm["name"] == "README"
    assert "## Index" not in (store / "README.md").read_text(encoding="utf-8")
    assert (store / "index.md").is_file()


def test_migrate_assigns_generic_type_and_derives_commit_when_both_absent(tmp_path):
    repo_root = tmp_path / "repo"
    store = repo_root / "docs" / "loom" / "memory"
    store.mkdir(parents=True)
    _write(store, "README.md", _legacy_readme(["[bare-fact](bare-fact.md) — No type or origin."]))
    _write(store, "bare-fact.md", _legacy_concept("bare-fact", "No type or origin.", type_=None, origin=None))
    _init_git_repo(repo_root)
    _commit_all(repo_root, "initial")

    mls.migrate(store, repo_root)

    fm = lm.parse_frontmatter((store / "bare-fact.md").read_text(encoding="utf-8"))
    assert fm["type"] == "Memory"
    resource = fm["sources"][0]["resource"]
    assert resource.startswith("introducing commit ")
    sha = resource.removeprefix("introducing commit ")
    assert len(sha) == 40
    # the derived commit is the one that actually introduced the file
    expected = mls.introducing_commit(repo_root, "docs/loom/memory/bare-fact.md")
    assert sha == expected


def test_migrate_preserves_unknown_extra_key(tmp_path):
    repo_root = tmp_path / "repo"
    store = repo_root / "docs" / "loom" / "memory"
    store.mkdir(parents=True)
    _write(store, "README.md", _legacy_readme(["[extra-key-fact](extra-key-fact.md) — Carries an extra key."]))
    _write(
        store,
        "extra-key-fact.md",
        "---\nname: extra-key-fact\ndescription: Carries an extra key.\ntype: gotcha\n"
        "origin: a fixture origin\ntype_note: legacy carryover\n---\n\nBody.\n",
    )
    _init_git_repo(repo_root)
    _commit_all(repo_root, "initial")

    mls.migrate(store, repo_root)

    fm = lm.parse_frontmatter((store / "extra-key-fact.md").read_text(encoding="utf-8"))
    assert fm["type_note"] == "legacy carryover"


def test_migrate_body_is_untouched(tmp_path):
    repo_root = tmp_path / "repo"
    store = repo_root / "docs" / "loom" / "memory"
    _make_legacy_store(store)
    _init_git_repo(repo_root)
    _commit_all(repo_root, "initial")

    before_text = (store / "a-fact.md").read_text(encoding="utf-8")
    _, before_body = mls.split_legacy(before_text)

    mls.migrate(store, repo_root)

    after_text = (store / "a-fact.md").read_text(encoding="utf-8")
    _, after_body = mls.split_legacy(after_text)
    assert after_body == before_body


def test_migrate_handles_description_with_colon_and_trailing_quote(tmp_path):
    """The real corpus has descriptions that both contain a colon and end
    in a literal `"` — a generic quoting dumper would corrupt these on
    re-parse (see module docstring). Guard the exact shape."""
    repo_root = tmp_path / "repo"
    store = repo_root / "docs" / "loom" / "memory"
    tricky = 'A gate must ENFORCE the default: never trust by default, unless "opted in"'
    store.mkdir(parents=True)
    _write(store, "README.md", _legacy_readme(["[tricky-fact](tricky-fact.md) — placeholder."]))
    _write(store, "tricky-fact.md", _legacy_concept("tricky-fact", tricky))
    _init_git_repo(repo_root)
    _commit_all(repo_root, "initial")

    mls.migrate(store, repo_root)

    fm = lm.parse_frontmatter((store / "tricky-fact.md").read_text(encoding="utf-8"))
    assert fm["description"] == tricky


# ---------------------------------------------------------------------------
# Acceptance A5 negative: no-implicit-migration-and-no-legacy-writer
# ---------------------------------------------------------------------------


def test_migrate_refuses_an_already_migrated_store_and_writes_nothing(tmp_path):
    repo_root = tmp_path / "repo"
    store = repo_root / "docs" / "loom" / "memory"
    store.mkdir(parents=True)
    _write(
        store,
        "README.md",
        "---\nname: README\ndescription: Charter.\ntype: Memory Store Guide\n"
        'sources:\n  - resource: "commit deadbeef"\n---\n\n# Guide\n',
    )
    _write(
        store,
        "a-fact.md",
        "---\nname: a-fact\ndescription: A description.\ntype: practice\n"
        'sources:\n  - resource: "a fixture origin"\n---\n\nThe fact body.\n',
    )
    lm.regenerate_index(store)
    before = {p.name: p.read_text(encoding="utf-8") for p in store.glob("*.md")}

    assert mls.is_legacy_store(store) is False
    try:
        mls.migrate(store, repo_root)
        raised = False
    except mls.MigrationError:
        raised = True
    assert raised

    after = {p.name: p.read_text(encoding="utf-8") for p in store.glob("*.md")}
    assert after == before


def test_migrate_refuses_a_store_with_no_index_heading_and_writes_nothing(tmp_path):
    repo_root = tmp_path / "repo"
    store = repo_root / "docs" / "loom" / "memory"
    store.mkdir(parents=True)
    _write(store, "README.md", "# Not a legacy store\n\nNo Index heading here.\n")
    _write(store, "a-fact.md", _legacy_concept("a-fact", "A description."))
    before = {p.name: p.read_text(encoding="utf-8") for p in store.glob("*.md")}

    assert mls.is_legacy_store(store) is False
    try:
        mls.migrate(store, repo_root)
        raised = False
    except mls.MigrationError:
        raised = True
    assert raised

    after = {p.name: p.read_text(encoding="utf-8") for p in store.glob("*.md")}
    assert after == before


def test_cli_refuses_and_exits_nonzero_without_writing(tmp_path):
    repo_root = tmp_path / "repo"
    store = repo_root / "docs" / "loom" / "memory"
    store.mkdir(parents=True)
    _write(store, "README.md", "# Not a legacy store\n")
    before = (store / "README.md").read_text(encoding="utf-8")

    result = subprocess.run(
        [sys.executable, str(SCRIPTS_DIR / "migrate_legacy_store.py"), str(store), "--repo-root", str(repo_root)],
        capture_output=True,
        text=True,
    )

    assert result.returncode == 1
    assert (store / "README.md").read_text(encoding="utf-8") == before


def test_no_other_script_in_the_repo_reads_the_legacy_readme_indexed_shape():
    """REQ-23: the migration command is the ONLY legacy-format reader."""
    legacy_markers = ("INDEX_LINE_RE", "def parse_index_lines", "def splice_index_section", "def build_entries")
    offenders = []
    for candidate_dir in (REPO_ROOT / "loom-memory" / "scripts",):
        for py in candidate_dir.glob("*.py"):
            if py.name in ("migrate_legacy_store.py", "test_migrate_legacy_store.py"):
                continue
            text = py.read_text(encoding="utf-8")
            if any(marker in text for marker in legacy_markers):
                offenders.append(py.name)
    assert offenders == []


def test_legacy_validator_and_its_tests_are_retired():
    """REQ-26: no surviving `--write` path can rewrite the migrated store —
    the legacy validator script and its README-index-specific tests are
    gone entirely."""
    assert not (REPO_ROOT / "scripts" / "check_loom_memory_integrity.py").exists()
    assert not (REPO_ROOT / "scripts" / "test_check_loom_memory_integrity.py").exists()


def test_loom_memory_cli_has_no_legacy_write_subcommand():
    """`loom_memory.py`'s own CLI exposes only `validate` and
    `regenerate-index` — no `--write`-style legacy rewriting subcommand
    survives outside `migrate_legacy_store.py` (REQ-26)."""
    result = subprocess.run(
        [sys.executable, str(SCRIPTS_DIR / "loom_memory.py"), "--help"],
        capture_output=True,
        text=True,
    )
    assert "--write" not in result.stdout
    assert "{validate,regenerate-index}" in result.stdout
