#!/bin/bash
# Codex manifest drift guard (shift-left for the loom-code CI codex-manifest-drift gate).
#
# Triggered: PostToolUse on Write|Edit (configured in .claude/settings.json).
#
# Why: loom-code ships two manifests that share fields (version, description, …):
#   loom-code/.claude-plugin/plugin.json   (canonical SSOT)
#   loom-code/.codex-plugin/plugin.json    (Codex mirror, generated by sync_codex_manifest.py)
# A version bump / shared-field edit to either, without re-running the sync, drifts
# the mirror and fails CI 8s after push. This catches it locally at the edit.
#
# Scope: only fires when one of the two plugin.json manifests is edited (no-op otherwise).
#
# Exit codes:
#   0 — in sync (or not a manifest edit)
#   2 — drift found (blocking; fix command printed to stderr)

set -e

INPUT=$(cat 2>/dev/null || echo '{}')

FILE_PATH=""
if command -v jq >/dev/null 2>&1; then
  FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // .tool_input.notebook_path // empty' 2>/dev/null || echo "")
fi

# Only relevant when a loom-code plugin manifest was touched.
case "$FILE_PATH" in
  */loom-code/.claude-plugin/plugin.json|*/loom-code/.codex-plugin/plugin.json) ;;
  *) exit 0 ;;
esac

# Derive repo root from the edited file's path (don't rely on cwd).
REPO_ROOT="${FILE_PATH%%/loom-code/*}"
SYNC="$REPO_ROOT/loom-code/scripts/sync_codex_manifest.py"
[ -f "$SYNC" ] || exit 0   # script absent (other repo / context) → harmless no-op

if ! PYTHONDONTWRITEBYTECODE=1 python3 "$SYNC" --check >/dev/null 2>&1; then
  cat >&2 <<EOF
❌ Codex manifest drift detected

loom-code/.codex-plugin/plugin.json no longer matches the shared fields of
loom-code/.claude-plugin/plugin.json (a version bump or shared-field edit was
not mirrored). The loom-code CI "codex-manifest-drift" gate will fail on push.

Fix (run from repo root):
    python3 loom-code/scripts/sync_codex_manifest.py

Then re-stage the regenerated .codex-plugin/plugin.json.
EOF
  exit 2
fi

exit 0
