#!/bin/bash
# Codex manifest drift guard (shift-left for the loom-code CI codex-manifest-drift gate).
#
# Triggered: PostToolUse on Write|Edit (configured in .claude/settings.json).
#
# Why: a Codex-eligible plugin ships two manifests that share fields
# (version, description, …):
#   <plugin>/.claude-plugin/plugin.json   (canonical SSOT)
#   <plugin>/.codex-plugin/plugin.json    (Codex mirror, generated by the shared
#                                          scripts/sync_codex_manifests.py engine)
# A version bump / shared-field edit to either, without re-running the sync, drifts
# the mirror and fails CI after push. This catches it locally at the edit.
#
# Scope: fires for ANY plugin's plugin.json manifest edit (no-op otherwise) —
# the plugin dir is derived from the edited path.
#
# Exit codes:
#   0 — in sync (or not a manifest edit)
#   2 — drift found (blocking; fix command printed to stderr)

set -e

INPUT=$(cat 2>/dev/null || echo '{}')

FILE_PATH=""
if command -v jq >/dev/null 2>&1; then
  FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // .tool_input.notebook_path // empty' 2>/dev/null || echo "")
fi

# Only relevant when a plugin manifest (either side) was touched. Derive the
# plugin directory by stripping the manifest suffix; don't rely on cwd.
case "$FILE_PATH" in
  */.claude-plugin/plugin.json) PLUGIN_DIR="${FILE_PATH%/.claude-plugin/plugin.json}" ;;
  */.codex-plugin/plugin.json)  PLUGIN_DIR="${FILE_PATH%/.codex-plugin/plugin.json}" ;;
  *) exit 0 ;;
esac

PLUGIN=$(basename "$PLUGIN_DIR")
REPO_ROOT=$(dirname "$PLUGIN_DIR")
SYNC="$REPO_ROOT/scripts/sync_codex_manifests.py"
[ -f "$SYNC" ] || exit 0   # shared engine absent (other repo / context) → harmless no-op

# This hook guards DRIFT only. A plugin with no Codex manifest yet is the
# scaffold step's concern (the engine reports it MISSING) — skip it here so a
# Claude-side edit on a Codex-less plugin stays a no-op.
[ -f "$PLUGIN_DIR/.codex-plugin/plugin.json" ] || exit 0

# Pass the absolute plugin dir so the check is cwd-independent (the engine
# accepts a plugin directory name OR path).

if ! PYTHONDONTWRITEBYTECODE=1 python3 "$SYNC" --check "$PLUGIN_DIR" >/dev/null 2>&1; then
  cat >&2 <<EOF
❌ Codex manifest drift detected

$PLUGIN/.codex-plugin/plugin.json no longer matches the shared fields of
$PLUGIN/.claude-plugin/plugin.json (a version bump or shared-field edit was
not mirrored). The CI "codex-manifest-drift" gate will fail on push.

Fix (run from repo root):
    python3 scripts/sync_codex_manifests.py $PLUGIN

Then re-stage the regenerated .codex-plugin/plugin.json.
EOF
  exit 2
fi

exit 0
