#!/usr/bin/env python3
"""Build the zh-CN <-> zh-TW pair glossary from NAER cross-strait CSV.

Source:
  vendor/naer/cross-strait.csv — columns: zh-CN, zh-TW, category
  (NAER 國家教育研究院 兩岸詞彙對照, primarily tech.software domain)

Domain inference reuses NAER_CATEGORY_TO_DOMAIN from build-pairs-from-en.py;
unmapped categories default to "general".

Output: scripts/canonical/glossary-zh-CN--zh-TW.md (BCP-47 alphabetical:
zh-CN < zh-TW), 4-column table per domain (zh-CN | zh-TW | source | notes).

Note: build-pairs-from-en.py has hyphens in its filename, so it is loaded
via importlib.util.spec_from_file_location rather than `import`.
"""
from __future__ import annotations

import argparse
import csv
import importlib.util
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_VENDOR_CSV = ROOT / "vendor" / "naer" / "cross-strait.csv"
DEFAULT_OUT = ROOT / "scripts" / "canonical"

PAIR = ("zh-CN", "zh-TW")  # BCP-47 alphabetical order
OUT_FILENAME = f"glossary-{PAIR[0]}--{PAIR[1]}.md"


def _load_build_pairs_module():
    """Load build-pairs-from-en.py as a module despite hyphens in filename."""
    src_path = Path(__file__).resolve().parent / "build-pairs-from-en.py"
    spec = importlib.util.spec_from_file_location("build_pairs_from_en", src_path)
    if spec is None or spec.loader is None:
        raise ImportError(f"could not load module from {src_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def parse_cross_strait_csv(csv_path: Path,
                           category_to_domain: dict[str, str]
                           ) -> dict[str, list[dict]]:
    """Parse the cross-strait CSV and group entries by inferred domain.

    Each entry is keyed by the BCP-47 pair locales so it slots straight into
    `emit_pair_file(pair=("zh-CN", "zh-TW"), entries_by_domain=...)`.
    """
    entries_by_domain: dict[str, list[dict]] = defaultdict(list)
    if not csv_path.exists():
        print(f"WARN: cross-strait CSV not found at {csv_path}; "
              f"emitting empty glossary file.", file=sys.stderr)
        return entries_by_domain

    with csv_path.open(encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        if not reader.fieldnames:
            return entries_by_domain
        for row in reader:
            zh_cn = (row.get("zh-CN") or "").strip()
            zh_tw = (row.get("zh-TW") or "").strip()
            category = (row.get("category") or "").strip()
            if not zh_cn or not zh_tw:
                continue
            domain = category_to_domain.get(category, "general")
            entries_by_domain[domain].append({
                "zh-CN": zh_cn,
                "zh-TW": zh_tw,
                "source": "naer-cross-strait",
                "notes": "—",
            })

    # Guard against silent column-name drift: file existed and was readable
    # but produced 0 entries — likely upstream renamed zh-CN / zh-TW columns.
    if not entries_by_domain:
        print(f"WARN: {csv_path} exists but yielded 0 entries — "
              f"column-name drift? expected columns: zh-CN, zh-TW, category",
              file=sys.stderr)
    return entries_by_domain


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build glossary-zh-CN--zh-TW.md from NAER cross-strait CSV.",
    )
    parser.add_argument("--cross-strait-csv", default=None,
                        help=f"Override cross-strait CSV path "
                             f"(default: {DEFAULT_VENDOR_CSV}).")
    parser.add_argument("--out-dir", default=None,
                        help=f"Override output directory "
                             f"(default: {DEFAULT_OUT}).")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    bp = _load_build_pairs_module()

    csv_path = Path(args.cross_strait_csv) if args.cross_strait_csv else DEFAULT_VENDOR_CSV
    out_dir = Path(args.out_dir) if args.out_dir else DEFAULT_OUT
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / OUT_FILENAME

    entries_by_domain = parse_cross_strait_csv(
        csv_path, bp.NAER_CATEGORY_TO_DOMAIN
    )
    if not entries_by_domain:
        print(f"WARN: no entries collected from {csv_path}; "
              f"emitting empty glossary file.", file=sys.stderr)

    bp.emit_pair_file(
        pair=PAIR,
        entries_by_domain=dict(entries_by_domain),
        out_path=out_path,
        generator_note="Generated by scripts/build-pair-zh-CN--zh-TW.py — do not hand-edit.",
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
