# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
"""Emit knowledge/_index.md for a packed bundle — the retrieval entry point.

Scans the bundle's FLAT knowledge/ dir and writes one line per frozen page,
grouped by page type, using the same canonical line shape as
init/assets/build_index_knowledge.py:

  - [<title>｜<title_local>](<slug>.md) `<status>` — <summary> 〔aka: a, b〕

Synthesis pages (type: synthesis) have no title/status; their line uses the
frontmatter `question` and a `synthesis` tag:

  - [<question>](<slug>.md) `synthesis` — verified deep-dive (<date>)

Derives everything from the frozen pages themselves (never from the source
.dbt-wiki/index.md, whose format varies by init version), so the index always
matches exactly what was frozen. Files starting with `_` are excluded
(_relations.md, _index.md itself). Pages with no recognized `type:` land in
an "Other pages" section — never silently dropped. Idempotent (overwrites
_index.md). Exits 1 when the dir holds no indexable page (a pack that froze
nothing is a failed pack).

Pure stdlib + pyyaml; no project specifics.

Usage:  uv run build_bundle_index.py <bundle>/knowledge
"""
import sys
from pathlib import Path

import yaml

SECTIONS = [
    ("knowledge-entity", "## Entities"),
    ("knowledge-metric", "## Metrics"),
    ("knowledge-concept", "## Concepts"),
    ("synthesis", "## Syntheses"),
    (None, "## Other pages"),
]

HEADER = """# Knowledge index

> Retrieval entry point for this bundle — one line per frozen page
> (title, status, one-line summary, aliases).
>
> **Consumption: grep-first.** Search this file for the question's
> business terms (`grep -i "<term>" _index.md`) — titles, summaries,
> and especially the 〔aka: …〕 aliases are the grep surface — then
> open only the pages the matching lines point to. Reading this whole
> file into context is the fallback for when grep misses, not the
> default. Regenerated by `dbt-wiki:pack` — do not edit by hand.
"""

# Bundle index summaries are capped (full summary lives on the page);
# the wiki-side init/assets/build_index_knowledge.py does NOT cap — same
# line shape, different summary length policy, both regenerate from page
# frontmatter so they never feed into each other.
SUMMARY_CAP = 80  # chars


def cap_summary(s: str) -> str:
    if len(s) <= SUMMARY_CAP:
        return s
    # search one char past the cap so a boundary straddling the edge
    # (e.g. ". " at 79-80) still counts
    head = s[: SUMMARY_CAP + 1]
    best = 0  # prefer the latest sentence boundary inside the cap
    for sep in ("。", "；", ". ", "; "):
        i = head.rfind(sep)
        if i >= 0:
            best = max(best, i + len(sep))
    if best > 0:
        return head[:best].rstrip()
    return s[:SUMMARY_CAP] + "…"


def parse_fm(text: str) -> dict:
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    try:
        fm = yaml.safe_load(text[3:end])
    except Exception:
        return {}
    return fm if isinstance(fm, dict) else {}


def line_for(path: Path, text: str) -> str:
    fm = parse_fm(text)
    if fm.get("type") == "synthesis":
        head = str(fm.get("question") or path.stem).strip()
        date = fm.get("date")
        tail = f"verified deep-dive ({date})" if date else "verified deep-dive"
        return f"- [{head}]({path.name}) `synthesis` — {tail}"
    title = fm.get("title") or path.stem
    tl = fm.get("title_local")
    status = fm.get("status") or "developing"
    summary = cap_summary(str(fm.get("summary") or "").strip())
    raw_aliases = fm.get("aliases") or []
    if isinstance(raw_aliases, str):  # scalar string -> one alias, not per-character
        raw_aliases = [raw_aliases]
    aliases = [str(a) for a in raw_aliases if a is not None and str(a).strip()]
    head = f"{title}｜{tl}" if tl else f"{title}"
    line = f"- [{head}]({path.name}) `{status}`"
    if summary:
        line += f" — {summary}"
    if aliases:
        line += f" 〔aka: {', '.join(aliases)}〕"
    return line


def build_index(kdir: Path) -> str:
    known_types = {t for t, _ in SECTIONS if t}
    grouped: dict[str | None, list[tuple[str, str]]] = {t: [] for t, _ in SECTIONS}
    total = 0
    for p in sorted(kdir.glob("*.md")):
        if p.name.startswith("_"):
            continue
        text = p.read_text(encoding="utf-8")
        fm = parse_fm(text)
        ptype = fm.get("type") if fm.get("type") in known_types else None
        grouped[ptype].append((p.stem.lower(), line_for(p, text)))
        total += 1

    out = [HEADER]
    for ptype, hdr in SECTIONS:
        rows = sorted(grouped[ptype])
        if ptype is None and not rows:
            continue  # omit "Other pages" when everything is typed
        out.append(hdr)
        out.append("")
        if rows:
            out.extend(r[1] for r in rows)
        else:
            out.append("_(none)_")
        out.append("")
    out.append(f"Total pages indexed: {total}")
    out.append("")
    return "\n".join(out)


def main(kdir: Path) -> int:
    pages = [p for p in kdir.glob("*.md") if not p.name.startswith("_")]
    if not pages:
        print(f"build_bundle_index: no knowledge pages found in {kdir} — "
              "freeze the knowledge layer (pack Step 2) first", file=sys.stderr)
        return 1
    text = build_index(kdir)
    (kdir / "_index.md").write_text(text, encoding="utf-8")
    print(f"build_bundle_index: indexed {len(pages)} pages -> {kdir / '_index.md'}")
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(2)
    sys.exit(main(Path(sys.argv[1])))
