"""test_us_statement_probe_fixture.py — pins the brief-cited measurements
from `docs/loom/specs/2026-07-26-us-as-reported-statement-lane.md`
§Probe evidence to the committed capture of the 2026-07-26 run over the
same 47-ticker corpus the kpi_id arc used
(`fixtures/capture_kpi_id_identity_probe.py:95-103`).

Every asserted number below is READ from the committed fixture
`fixtures/us_statement_shapes_probe_2026-07-26.json` (regenerated by
`fixtures/capture_us_statement_shapes_probe.py`) — never hand-typed, per
repo memory `hand-authored-fixture-is-a-fabrication-risk`.

Offline: fixture-only, no network marker, part of the default
`not network` suite:
  PYTHONDONTWRITEBYTECODE=1 uv run --quiet --with pytest --with 'pyyaml>=6.0' \
    pytest investing-toolkit/tests/ -m "not network" -q
"""
from __future__ import annotations

import json
from pathlib import Path

_FIXTURE = Path(__file__).parent / "fixtures" / "us_statement_shapes_probe_2026-07-26.json"


def test_fixture_pins_the_brief_cited_measurements():
    doc = json.loads(_FIXTURE.read_text())
    summary = doc["_summary"]

    assert summary["n_filers_probed"] == 47
    assert summary["n_filers_zero_us_gaap_concepts"] == 1
    assert summary["n_filers_never_tagging_total_liabilities"] == 13
    assert summary["n_filers_shipped_lane_truncated_1y_or_more"] == 10
    assert summary["n_filers_usable_history_ge_20y"] == 0
