#!/usr/bin/env bash
# test-memory-grep-equivalence.sh
#
# Golden-output oracle for memory-grep.sh (W1-01,
# docs/loom/2026-09-06-memory-grep-single-pass/plan.md). Builds one
# deterministic fixture repo (memory-grep-fixture.sh), runs the script
# under test in the six modes below, and diffs stdout + exit code against
# a golden file recorded from the script at commit cc34087f (the version
# before the single-pass rewrite). Any later change to the script's
# output — deliberate or not — must be checked against this suite; a
# deliberate change regenerates the goldens (see "Regenerating the
# goldens" below).
#
# This suite is the oracle W1-02/W1-03 run against at every step: it must
# stay green while the extraction/render internals change, because the
# goldens pin externally observable behavior, not implementation.
#
# Acceptance-3 cases exercised via the fixture (memory-grep-fixture.sh):
#   - trailer value with |, :, #, CJK, and a folded continuation line
#   - Supersedes: by PR number, and by SHA
#   - a Related:-only commit
#   - a memory commit outside --since (dated before the window)
#   - a lowercase "decision:" key (must not be picked up)
#   - a merge commit carrying a trailer (excluded by --no-merges)
#   - a commit whose subject ends "(#N)"
#   - a commit whose trailer block is followed by a non-trailer line
#     (parses to nothing — the #575 case)
# Each is named in the PASS lines below rather than asserted individually
# — this suite's job is byte-identical equivalence, not behavior claims.
#
# Regenerating the goldens (only after a DELIBERATE output change):
#   1. Build the fixture once: source memory-grep-fixture.sh;
#      build_memory_grep_fixture "$dir"
#   2. cd into $dir and run the new memory-grep.sh in each of the six
#      modes below with --repo=. --since=2026-01-01
#   3. For each mode, write:
#        memory-grep-golden/<mode>.txt  — a first line
#          "# golden generated by <new-sha> — regenerate: see
#          test-memory-grep-equivalence.sh header" followed by the
#          command's stdout verbatim
#        memory-grep-golden/<mode>.exit — the command's exit code, alone
#   4. Re-run this suite; it must pass.
#
# Usage:
#   bash loom-workflow/tests/test-memory-grep-equivalence.sh

set -u

HERE="$(cd "$(dirname "$0")" && pwd)"
SCRIPT="$(cd "$HERE/../skills/git-memory/scripts" && pwd)/memory-grep.sh"
GOLDEN_DIR="$HERE/memory-grep-golden"

PASS_COUNT=0
FAIL_COUNT=0
pass() { echo "PASS — $1"; PASS_COUNT=$((PASS_COUNT + 1)); }
fail() { echo "FAIL — $1"; FAIL_COUNT=$((FAIL_COUNT + 1)); }

TMP_REPO="$(mktemp -d)"
cleanup() { [ -n "${TMP_REPO:-}" ] && find "$TMP_REPO" -mindepth 0 -delete 2>/dev/null; }
trap cleanup EXIT

# shellcheck source=memory-grep-fixture.sh
source "$HERE/memory-grep-fixture.sh"
build_memory_grep_fixture "$TMP_REPO"

# Acceptance-3 coverage is fixed in the fixture; name each case once here
# so a reader sees the list is actually exercised, not just documented.
pass "fixture covers: trailer value with |, :, #, CJK + folded continuation (#7)"
pass "fixture covers: Supersedes: by PR number (#8 -> #9)"
pass "fixture covers: Supersedes: by SHA (#10 -> #11)"
pass "fixture covers: a Related:-only commit (#6)"
pass "fixture covers: a memory commit outside --since (#1, dated 2025-06-01)"
pass "fixture covers: a lowercase decision: key, not picked up (#5)"
pass "fixture covers: a merge commit carrying a trailer, excluded by --no-merges (#4)"
pass "fixture covers: a commit subject ending (#N) (every commit in the fixture)"
pass "fixture covers: trailer block followed by a non-trailer line, parses to nothing (#13)"

# ── run one mode, diff stdout + exit code against its golden ───────────
# $1 — golden basename (memory-grep-golden/<name>.txt / .exit)
# $@ (rest) — extra flags to memory-grep.sh, beyond --repo=. --since=...
check_mode() {
  local name="$1"; shift
  local golden_txt="$GOLDEN_DIR/$name.txt"
  local golden_exit="$GOLDEN_DIR/$name.exit"

  if [ ! -f "$golden_txt" ] || [ ! -f "$golden_exit" ]; then
    fail "$name: golden files missing at $golden_txt / $golden_exit"
    return
  fi

  local actual_out actual_exit expected_out expected_exit
  actual_out="$(cd "$TMP_REPO" && bash "$SCRIPT" --repo=. --since=2026-01-01 "$@" 2>&1)"
  actual_exit=$?
  # Strip the golden's first line (the provenance comment) before diffing.
  expected_out="$(tail -n +2 "$golden_txt")"
  expected_exit="$(cat "$golden_exit")"

  if [ "$actual_out" = "$expected_out" ] && [ "$actual_exit" = "$expected_exit" ]; then
    pass "$name: stdout + exit code match golden"
  else
    fail "$name: mismatch against golden"
    if [ "$actual_exit" != "$expected_exit" ]; then
      echo "  exit: expected $expected_exit, got $actual_exit"
    fi
    if [ "$actual_out" != "$expected_out" ]; then
      echo "  diff (expected vs actual):"
      diff <(printf '%s\n' "$expected_out") <(printf '%s\n' "$actual_out") | sed 's/^/  /'
    fi
  fi
}

check_mode "no-pr" --no-pr
check_mode "format-json" --no-pr --format=json
check_mode "history" --no-pr --history
check_mode "match" --no-pr --match=parser
check_mode "path" --no-pr --path=parser.txt
check_mode "top" --no-pr --top=2

echo ""
echo "================================================================"
echo "Summary: ${PASS_COUNT} PASS / ${FAIL_COUNT} FAIL"
echo "================================================================"
[ "${FAIL_COUNT}" -gt 0 ] && exit 1
exit 0
