#!/usr/bin/env python3
"""A runtime prose contract cites only what ships with it.

Scans `loom-code/skills/**/*.md`, `loom-code/agents/*.md` (non-recursive —
that directory is flat) and `loom-design/skills/**/*.md` for a
backtick-quoted citation of a file under THIS repository's `docs/`
development records (a dated entry under `specs/`, `plans/`, `audits/`,
`design/`, `research/`, `dogfood/`, `backlog/`, or a named entry under
`memory/`, etc.) — a path applicable only in `monkey-skills` itself, never
in a repo that merely installed loom. Only `.md` files are scanned: a `.py`
or `.sh` comment reaches no model, so those are out of scope by design (see
`docs/loom/specs/2026-08-22-contracts-cite-only-what-ships.md`, this
script's own governing spec).

A citation counts wherever it appears — backticked or in plain prose. An
earlier revision extracted only from backtick spans, claiming those were the
shape every real citation uses. That was false, and it left the gate blind: a
dated record cited in bare prose sat three lines from a backticked one and the
checker printed OK. External URLs containing `docs/` are excluded by the
`docs/loom` prefix filter instead, which is what actually did that work all
along — no URL in this corpus contains `docs/loom`.

The exemption boundary is PROTOCOL versus RECORD, not directory versus
filename. A path loom defines for every host repository is exempt whatever
its shape; a path naming one of THIS repository's development records is a
citation, whichever directory holds it. Concretely, a `docs/loom/...`
candidate is exempt (never a citation) when any of these hold:

  - it names a directory, not a file — its final path segment carries no
    extension (e.g. `docs/loom/plans/`, `docs/loom/memory`, `docs/loom/`,
    `docs/loom/spec/`, `docs/**`) AND no path segment carries a literal
    `YYYY-MM-DD`. Any store loom scaffolds for a host repo is exempt this
    way, whatever the store is named; a dated folder such as
    `docs/loom/archive/2026-08-13-some-change` is one of THIS repo's
    records and is banned, directory or not. The closed protocol-filename
    list below is for named FILES only;
  - it contains a `<...>` template placeholder, or is the `docs/**` glob —
    a grammar SHAPE the host repo will instantiate, not a citation of an
    existing document (e.g. `docs/loom/specs/<date>-<topic>.md`,
    `docs/loom/discovery/<date>-<slug>/evidence.md`,
    `docs/loom/spec/<capability>/README.md`);
  - its final path segment is one of the closed protocol filenames every
    host repo owns: `PRINCIPLES.md`, `PURPOSE.md`, `KICKOFF-DEFAULTS.md`,
    `INDEX.md`, `DESIGN.md`, `QUEUE.toml`, a store's own `README.md`,
    `ui-flows.md`, `queue-state.json` — or the path ends in the specific
    `spec/MODEL.md` (that literal parent+file pair only, not any
    `MODEL.md` anywhere).

Everything else naming a real file under `docs/loom/` is BANNED: a citation
of this repository's own development record.

`DEBT_LIST` is a shrink-only literal naming every file that violates today
— generated by running this checker's own `scan_repo()` over the tree, per
the plan's Task 1 (never by transcribing a count from the plan or brief;
independent hand-counts of this corpus disagreed with each other).
`evaluate()` fails on EITHER direction of drift: a violating file absent
from `DEBT_LIST` (a new violation slipped in), or a listed file that no
longer violates (the list must be edited down as files are cleaned, never
left to over-claim debt that no longer exists).

Stdlib only.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# (relative-to-repo-root directory, recursive?) pairs defining the scan
# scope. `loom-code/agents` is intentionally non-recursive — that
# directory is flat by this repo's own skill-structure convention.
_SCOPE_DIRS: tuple[tuple[str, bool], ...] = (
    ("loom-code/skills", True),
    ("loom-code/agents", False),
    ("loom-design/skills", True),
    ("loom-code/scripts/templates", False),
)

# One backtick-delimited span, single line (every real citation in this
# corpus is written this way; a triple-backtick fenced block spanning
# multiple lines is not a citation site in this corpus).
_BACKTICK_RE = re.compile(r"`([^`\n]+)`")

# A `docs/...`-shaped candidate inside a backtick span, up to the next
# whitespace — isolates the path out of a longer backticked command
# (e.g. `` `git add docs/loom/archive/<date>-<change-id>/` ``).
# Path-shaped characters only. `docs/\S*` was safe while extraction ran
# inside backtick spans, whose delimiters were already stripped; scanning
# plain text it swallowed the trailing backtick, comma or paren and broke the
# protocol-basename comparison (`PRINCIPLES.md\`` != `PRINCIPLES.md`).
_DOCS_CANDIDATE_RE = re.compile(r"docs/[A-Za-z0-9_.<>*/-]+")

# A literal `YYYY-MM-DD` inside a path segment: the mark of one dated
# record rather than a store. Directory citations carrying one are banned.
_DATED_SEGMENT_RE = re.compile(r"/\d{4}-\d{2}-\d{2}")

# Trailing `:<line>` or `:<line>-<line>` citation-line suffix, stripped
# before classifying (it never changes exempt/banned status).
_TRAILING_LINE_RE = re.compile(r":\d+(?:-\d+)?$")

# A `<...>` template placeholder segment — the signal a candidate is a
# grammar SHAPE, not a citation of an existing document.
_PLACEHOLDER_RE = re.compile(r"<[^>]+>")

# The closed protocol-filename list — every host repo owns these,
# whatever directory holds them. `README.md` covers a store's own
# README (`docs/loom/backlog/README.md`, `docs/loom/memory/README.md`,
# ...); `spec/MODEL.md` is handled separately below since it is a
# specific parent+file pair, not a bare basename.
_PROTOCOL_BASENAMES = frozenset(
    {
        "PRINCIPLES.md",
        "PURPOSE.md",
        "KICKOFF-DEFAULTS.md",
        "INDEX.md",
        "DESIGN.md",
        "QUEUE.toml",
        "README.md",
        "ui-flows.md",
        "queue-state.json",
        # Generated index of the backlog store; every adopting repo has one,
        # written by `backlog_index.py --write`. Surfaced when the scope
        # widened to `scripts/templates/`, whose backlog charter cites it.
        "BACKLOG.md",
    }
)


def classify_citation(candidate: str) -> str:
    """Return `"exempt"` or `"banned"` for one extracted `docs/...` candidate.

    See the module docstring for the full protocol-versus-record rule this
    implements.
    """
    path = _TRAILING_LINE_RE.sub("", candidate)
    if "**" in path or _PLACEHOLDER_RE.search(path):
        return "exempt"
    if path.endswith("spec/MODEL.md"):
        return "exempt"
    stripped = path.rstrip("/")
    basename = stripped.rsplit("/", 1)[-1]
    if basename in _PROTOCOL_BASENAMES:
        return "exempt"
    if "." not in basename:
        # A bare directory citation. Exempt as a loom-scaffolded store —
        # UNLESS a segment carries a literal date, which means it names one
        # specific record rather than a store every host repo owns:
        # `docs/loom/archive/2026-08-13-some-change` is this repo's history,
        # `docs/loom/backlog` is anyone's store. Placeholder shapes such as
        # `docs/loom/discovery/<date>-<slug>` never reach here — the `<...>`
        # rule above exempts them first.
        if _DATED_SEGMENT_RE.search(stripped):
            return "banned"
        return "exempt"
    return "banned"


def extract_docs_candidates(text: str) -> list[str]:
    """Return every `docs/loom/...`-shaped candidate in `text`.

    Scans the WHOLE text, not only backtick spans. An earlier revision
    extracted only from inside backticks, on the stated ground that backticks
    were "the shape every real citation in this corpus uses". That was false:
    a whole-branch reviewer found a dated record cited in plain prose three
    lines from a backticked one, invisible to the gate. Since the gate exists
    to catch every new citation, a contributor omitting backticks defeated it
    entirely and the script still printed OK.

    The backtick constraint had been added to exclude external URLs
    containing `docs/`, but the prefix filter below already does that: the two
    such URLs in this corpus are `.../docs/core/display/material` and
    `.../docs/en/workflows.md`, neither of which starts `docs/loom`. No URL in
    this corpus contains `docs/loom`, so scanning plain text costs nothing.

    Only candidates that could plausibly be one of this repo's `docs/loom`
    citations are returned — `docs/loom...`, the `docs/**` glob, or a
    `docs/<placeholder>...` shape.
    """
    candidates: list[str] = []
    for cand_match in _DOCS_CANDIDATE_RE.finditer(text):
            cand = cand_match.group(0).rstrip(".,;:-")
            if (
                cand.startswith("docs/loom")
                or cand.startswith("docs/**")
                or cand.startswith("docs/<")
            ):
                candidates.append(cand)
    return candidates


def find_banned_citations(text: str) -> list[str]:
    """Return every BANNED `docs/...` citation candidate found in `text`."""
    return [
        cand
        for cand in extract_docs_candidates(text)
        if classify_citation(cand) == "banned"
    ]


def iter_scope_files(repo_root: Path) -> list[Path]:
    """Every `.md` file under the scan scope, sorted for determinism."""
    files: list[Path] = []
    for rel_dir, recursive in _SCOPE_DIRS:
        base = repo_root / rel_dir
        if not base.is_dir():
            continue
        pattern = "**/*.md" if recursive else "*.md"
        files.extend(base.glob(pattern))
    return sorted(files)


def scan_repo(repo_root: Path) -> dict[str, list[str]]:
    """Map repo-root-relative posix path -> its banned citations, for every
    scoped file that has at least one. A file with zero banned citations is
    absent from the result (it does not violate)."""
    violators: dict[str, list[str]] = {}
    for path in iter_scope_files(repo_root):
        text = path.read_text(encoding="utf-8")
        banned = find_banned_citations(text)
        if banned:
            violators[path.relative_to(repo_root).as_posix()] = banned
    return violators


def evaluate(
    actual_violators: set[str], debt_list: frozenset[str]
) -> tuple[bool, list[str]]:
    """Compare the files that actually violate today against `debt_list`.

    Fails in EITHER direction: a violating file missing from `debt_list`
    (a new violation), or a listed file that no longer violates (the list
    must shrink as files are cleaned, never be left stale). Returns
    `(ok, messages)`; `ok` is `True` only when the two sets match exactly.
    """
    unlisted = sorted(actual_violators - debt_list)
    stale = sorted(debt_list - actual_violators)
    messages = [f"NEW VIOLATION (not in debt list): {f}" for f in unlisted]
    messages += [
        f"STALE DEBT ENTRY (no longer violates, remove from DEBT_LIST): {f}"
        for f in stale
    ]
    return (len(messages) == 0, messages)


# Generated by running `scan_repo()` over this repository — see the module
# docstring. Never hand-edited by count; regenerate via:
#   python3 -c "from pathlib import Path; from check_contract_citations \
#     import scan_repo; print('\n'.join(sorted(scan_repo(Path('.')))))"
DEBT_LIST: frozenset[str] = frozenset(
    {
        "loom-code/skills/finishing-a-development-branch/SKILL.md",
        "loom-code/skills/requesting-code-review/SKILL.md",
        "loom-code/skills/requesting-code-review/references/design-evidence.md",
        "loom-code/skills/requesting-code-review/references/gate-markers-spec.md",
        "loom-code/skills/requesting-docs-review/SKILL.md",
        "loom-code/skills/requesting-docs-review/references/convergence-contract.md",
        "loom-code/skills/requesting-docs-review/references/design-evidence.md",
        "loom-code/skills/subagent-driven-development/SKILL.md",
        "loom-code/skills/subagent-driven-development/references/dispatch-hygiene-notes.md",
        "loom-code/skills/subagent-driven-development/references/research-escalation.md",
        "loom-code/skills/ui-verification/SKILL.md",
        "loom-code/skills/using-loom-code/references/codex-tools.md",
        "loom-code/skills/writing-plans/SKILL.md",
        "loom-code/skills/writing-plans/references/design-evidence.md",
        "loom-code/skills/writing-plans/references/kickoff-briefing.md",
        "loom-code/skills/writing-plans/references/plan-document-reviewer-prompt.md",
        "loom-code/skills/writing-plans/references/plan-format.md",
        "loom-design/skills/completeness-critic/SKILL.md",
        "loom-design/skills/completeness-critic/references/consistency-lens.md",
        "loom-design/skills/design-system/references/canon-design-surface.md",
        "loom-design/skills/product-principles/references/canon-design-interaction.md",
        "loom-design/skills/product-principles/references/canon-design-visual.md",
        "loom-design/skills/product-principles/references/canon-engineering.md",
        "loom-design/skills/product-principles/references/canon-product.md",
        "loom-design/skills/product-principles/references/question-sets.md",
        "loom-design/skills/using-loom-pipeline/SKILL.md",
    }
)


def find_repo_root(start: Path) -> Path:
    """Walk up from `start` to the nearest `.git` dir; else cwd."""
    current = start.resolve()
    for parent in (current, *current.parents):
        if (parent / ".git").exists():
            return parent
    return Path.cwd()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Check that every runtime prose contract under the scope "
            "cites only files that ship with it, against a shrink-only "
            "debt list of today's known violators."
        )
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        help="repo root to scan (default: nearest .git ancestor of this script)",
    )
    args = parser.parse_args(argv)

    repo_root = args.repo_root or find_repo_root(Path(__file__).parent)
    actual = scan_repo(repo_root)
    ok, messages = evaluate(set(actual.keys()), DEBT_LIST)

    if not ok:
        for message in messages:
            print(message, file=sys.stderr)
        # New violations carry their offending citations for the fixer.
        for rel_path in sorted(set(actual) - DEBT_LIST):
            for cand in actual[rel_path]:
                print(f"    {rel_path}: {cand}", file=sys.stderr)
        return 1

    print(
        f"OK: {len(DEBT_LIST)} known-violating files unchanged, "
        "no new contract citations of this repo's records."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
